const petAnimals = [
  {
    id: 1,
    name: "Golden Retriever Puppy",
    age: "8 weeks",
    breed: "Golden Retriever",
    colors: ["Golden", "Cream"],
    price: 15000,
    description: "A friendly and playful Golden Retriever puppy.",
    gender: "Male",
    vaccinations: ["Rabies", "Distemper", "Parvovirus"],
    stock: 5,
    images: [
      "https://i.postimg.cc/XY7bwYf1/golden-retriever-puppy1.png",
      "https://i.postimg.cc/wTGfmpS1/golden-retriever-puppy2.png",
    ],
  },
  {
    id: 2,
    name: "Siamese Kitten",
    age: "12 weeks",
    breed: "Siamese",
    colors: ["Cream", "Brown"],
    price: 8000,
    description: "A beautiful Siamese kitten with striking blue eyes.",
    gender: "Female",
    vaccinations: ["Rabies", "Feline Leukemia", "Panleukopenia"],
    stock: 8,
    images: [
      "https://i.postimg.cc/8PBd7KcT/siamese-kitten1.png",
      "https://i.postimg.cc/7Zj7yVt4/siamese-kitten2.png",
    ],
  },
  {
    id: 3,
    name: "Budgerigar",
    age: "6 months",
    breed: "Budgerigar",
    colors: ["Green", "Blue", "Yellow"],
    price: 500,
    description: "A colorful and cheerful budgerigar.",
    gender: "Male",
    vaccinations: ["Avian Influenza"],
    stock: 20,
    images: [
      "https://i.postimg.cc/65ZJYbkM/budgerigar1.png",
      "https://i.postimg.cc/yxZbpmXX/budgerigar2.png",
    ],
  },
  {
    id: 4,
    name: "Rabbit",
    age: "4 months",
    breed: "Holland Lop",
    colors: ["White", "Brown", "Black"],
    price: 2500,
    description: "A cute and cuddly Holland Lop rabbit.",
    gender: "Female",
    vaccinations: ["Myxomatosis", "Rabbit Hemorrhagic Disease"],
    stock: 10,
    images: [
      "https://i.postimg.cc/Zn0dq5xz/rabbit1.png",
      "https://i.postimg.cc/GhrZtPqt/rabbit2.png",
    ],
  },
  {
    id: 5,
    name: "Hamster",
    age: "3 months",
    breed: "Syrian Hamster",
    colors: ["Golden", "White", "Black"],
    price: 700,
    description: "A small and active Syrian hamster.",
    gender: "Male",
    vaccinations: ["None required"],
    stock: 15,
    images: [
      "https://i.postimg.cc/fRC8mz9F/hamster1.png",
      "https://i.postimg.cc/sgjy0YXy/hamster2.png",
    ],
  },
  {
    id: 6,
    name: "Cockatiel",
    age: "5 months",
    breed: "Cockatiel",
    colors: ["Grey", "White", "Yellow"],
    price: 3000,
    description: "A friendly and sociable cockatiel.",
    gender: "Female",
    vaccinations: ["Avian Influenza"],
    stock: 12,
    images: [
      "https://i.postimg.cc/D0JnqP6P/cockatiel1.png",
      "https://i.postimg.cc/Y0g4pHgJ/cockatiel2.png",
    ],
  },

  {
    id: 8,
    name: "Turtle",
    age: "1 year",
    breed: "Red-Eared Slider",
    colors: ["Green", "Yellow"],
    price: 2000,
    description: "A calm and easy-to-care-for Red-Eared Slider turtle.",
    gender: "Female",
    vaccinations: ["None required"],
    stock: 25,
    images: [
      "https://i.postimg.cc/Y0JxG4cR/turtle1.png",
      "https://i.postimg.cc/x8dJk2DF/turtle2.png",
    ],
  },
];

export default petAnimals;
